import React from 'react';
import '../css/Project.css';
import MainContainer from './MainContainer';
import ProjectDetail from './ProjectDetail';
import { TweenMax } from 'gsap';
import Parallax from 'react-rellax';

export default class Project extends React.Component{

    constructor(props){
        super(props);

        this.state = {
            array : [
                {
                    class : "pro1",
                    title : "Real Chat",
                    language : "NodeJS, Socket, Javascript, HTML, Jade, CSS, MySQL",
                    content : "Through socket.io module, Made up to represent the message from A user to B user's computer simultaneously. Also, the user information is stored in MySQL.",
                    github : "https://github.com/Cool-Hongsi/Real-Chat-Version-2"
                },
                {
                    class : "pro2",
                    title : "School Course",
                    language : "NodeJS, Javascript, Jade, CSS, PostgreSQL, MongoDB, GoogleAPI",
                    content : "Put login and signup functions as well as used two types of databases in order to store course information in PostgreSQL and user information in MongoDB. Also, considered well-organized design and used Google Passport API to make login easily via google account. In order to build up security, all passwords are generated by bcrypt and salt.",
                    github : "https://github.com/Cool-Hongsi/Seneca-Course-Application"
                },
                {
                    class : "pro3",
                    title : "Shopping Cart",
                    language : "MVC (ReactJS, NodeJS, MongoDB), REST API, session, fetch, ES6",
                    content : " As the standard of MVC design, stored product list information into MongoDB and send the data from one of the routers in NodeJS. After then, set up the proxy server as the same server of NodeJS, and receive the data by using fetch method in ReactJS. Also, represent data through ES6 (spread, includes).",
                    github : "https://github.com/Cool-Hongsi/shoppingcart"
                },
                {
                    class : "pro4",
                    title : "Manage Info",
                    language : "ReactJS, ES6, router, axios",
                    content : "Extract data that I would like to receive through API (with axios), Represent data in ReactJS. Also, by using router, show each data as I set up the router path.",
                    github : "https://github.com/Cool-Hongsi/React-Manage-Employee"
                },
                {
                    class : "pro5",
                    title : "Shopping Mall",
                    language : "E-Commerce (Shopify)",
                    content : "Create online shopping mall website by using E-Commerce Platform (Shopify)",
                    github : "https://purenatures.ca"
                }
            ]
        }
    };

    componentDidMount(){

        TweenMax.to(".project-show-outside", 1, {
            delay: 3.8,
            display: "none"
        });

        // Effect to nav tag in MainContainer
        TweenMax.to("nav", 2, {
            delay: 4.5,
            opacity: 1
        });
        
        // Effect to nav ul li a tag in MainContainer
        TweenMax.to("nav ul li a", 2, {
            delay: 4.5,
            cursor: "pointer"
        });

        TweenMax.to(".letter", 1, {
            delay: 5.5,
            opacity: .2
        });

        TweenMax.to(".project-detail-outside", 2, {
            delay: 6,
            display: "block",
            opacity: 1
        });
    }

    render(){
        return(
            <MainContainer>

                <div className="project-show-outside">
                    <div className="project-show-inside">
                        What I Create ?
                    </div>
                </div>
                
                <div className="project-detail-outside">
                    {this.state.array.map((el, index) => {
                        return(
                            <div key={index}>
                                <ProjectDetail class={el.class} title={el.title} language={el.language} content={el.content} github={el.github} />
                            </div>
                        )
                    })}
                </div>
                
                <div className="project-detail-outside">
                    <Parallax className="letter letter1" speed={4}>P</Parallax>
                    <Parallax className="letter letter2" speed={5}>R</Parallax>
                    <Parallax className="letter letter3" speed={6}>O</Parallax>
                    <Parallax className="letter letter4" speed={4}>J</Parallax>
                    <Parallax className="letter letter5" speed={5}>E</Parallax>
                    <Parallax className="letter letter6" speed={6}>C</Parallax>
                    <Parallax className="letter letter7" speed={7}>T</Parallax>
                </div>

            </MainContainer>
        )
    }
}